# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField()),
                ('Precio', models.FloatField()),
                ('Adquiriente', models.CharField(max_length=12)),
                ('Puesto', models.IntegerField()),
                ('Origen', models.CharField(choices=[(b'ciudad 1', b'Guayaquil'), (b'ciudad 2', b'Quito'), (b'ciudad 3', b'Manta'), (b'ciudad 4', b'Machala'), (b'ciudad 5', b'Babahoyo')], max_length=20)),
                ('Destino', models.CharField(choices=[(b'ciudad 1', b'Guayaquil'), (b'ciudad 2', b'Quito'), (b'ciudad 3', b'Manta'), (b'ciudad 4', b'Machala'), (b'ciudad 5', b'Babahoyo')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
