# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField()),
                ('Origen', models.CharField(max_length=30)),
                ('Destino', models.CharField(max_length=30)),
                ('Precio', models.FloatField()),
                ('Adquiriente', models.CharField(max_length=12)),
                ('Puesto', models.IntegerField()),
            ],
        ),
    ]
