# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Origen',
            field=models.CharField(choices=[('ciudad 1', 'Freshman'), ('ciudad 2', 'Sophomore'), ('ciudad 3', 'Junior'), ('ciudad 4', 'Senior')], max_length=2),
        ),
    ]
