# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20170809_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Destino',
            field=models.CharField(choices=[('ciudad 1', 'Guayaquil'), ('ciudad 2', 'Quito'), ('ciudad 3', 'Manta'), ('ciudad 4', 'Machala'), ('ciudad 5', 'Babahoyo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Origen',
            field=models.CharField(choices=[('ciudad 1', 'Guayaquil'), ('ciudad 2', 'Quito'), ('ciudad 3', 'Manta'), ('ciudad 4', 'Machala'), ('ciudad 5', 'Babahoyo')], max_length=2),
        ),
    ]
